INSERT INTO ACTOR VALUES (1,'Anisha','f');
INSERT INTO ACTOR VALUES (2,'Pavan','m');
INSERT INTO ACTOR VALUES (3,'Pradeep','m');
INSERT INTO ACTOR VALUES (4,'George','m');

INSERT INTO DIRECTOR VALUES (1,'Rohit', 1234567890);
INSERT INTO DIRECTOR VALUES (2,'Akash', 1345678901);
INSERT INTO DIRECTOR VALUES (3,'Christopher', 1456789012);
INSERT INTO DIRECTOR VALUES (4,'Pamela', 1567890123);

INSERT INTO MOVIES VALUES (1,'ABCD', 2020, 'Hindi', 1);
INSERT INTO MOVIES VALUES (2,'BCDA', 2019, 'Telugu', 1);
INSERT INTO MOVIES VALUES (3,'CDAB', 2021, 'English', 2); 
INSERT INTO MOVIES VALUES (4,'DABC', 2018, 'Kannada', 3);
INSERT INTO MOVIES VALUES (5,'HHHH', 2021, 'Kannada', 4);

 -- use to avoid foreign key constraint errors --
 
SET FOREIGN_KEY_CHECKS=0;
    
INSERT INTO MOVIE_CAST VALUES (1, 2, 'Actress'); 
INSERT INTO MOVIE_CAST VALUES (1, 1, 'Actress'); 
INSERT INTO MOVIE_CAST VALUES (3, 3, 'Actor'); 
INSERT INTO MOVIE_CAST VALUES (3, 2, 'Villain'); 
INSERT INTO MOVIE_CAST VALUES (4, 4, 'Actor');


    
INSERT INTO RATING VALUES (1,4);
INSERT INTO RATING VALUES (2,2);
INSERT INTO RATING VALUES (3, 5);
INSERT INTO RATING VALUES (4, 4);
-- delete from rating where  mov_id=5; --
INSERT INTO RATING VALUES (5, 0);
